[package]
name = "gradual_int_sqrt"
version = "0.1.0"
authors = ["Nicholas Sterling <Nicholas.Sterling@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
more-asserts = "0.2"
